### ISSUE TITLE
Use YAML template for repeating sections in CI

### ISSUE THREAD

**Issue by nikosavola** [nikosavola/python-template#1]
The steps such as
```
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pythonLocation }}-pip-
```
should be turned into a YAML template. Alternatively, only the caching could be shortened.
